//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketsMVC.SentenciasSQL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _SQLCliente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _SQLCliente() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketsMVC.SentenciasSQL._SQLCliente", typeof(_SQLCliente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a answer_cliNew @userName,@TicketUUID,@TeamViewer,@Mensaje,@Observaciones,@Archivo1,@Archivo2,@Archivo3.
        /// </summary>
        internal static string GuardaAnswer {
            get {
                return ResourceManager.GetString("GuardaAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ticket_cliNew @userName,@TeamViewer,@Mensaje,@Observaciones,@Archivo1,@Archivo2,@Archivo3.
        /// </summary>
        internal static string GuardaTickets {
            get {
                return ResourceManager.GetString("GuardaTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ticket_cliIndex @userName,@startIndex,@perPage.
        /// </summary>
        internal static string RecuperaTickets {
            get {
                return ResourceManager.GetString("RecuperaTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ticket_cliDetalle @UUID.
        /// </summary>
        internal static string RecuperaTicketsDET {
            get {
                return ResourceManager.GetString("RecuperaTicketsDET", resourceCulture);
            }
        }
    }
}
